// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwybftdmeqniuvxglrzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3eWJmdGRtZXFuaXV2eGdscnpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDI3MTIsImV4cCI6MjA2MTUxODcxMn0.JEN_q8hmt-9w6dfGQH1PRkL7k_i6Im42TKfxcT8gENA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});